name: Test Build on Development PR

on:
    pull_request:
        branches:
            - development

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install dependencies
              run: npm install

            - name: Run build
              run: npm run build
